// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using spor_proje_api.Data;

#nullable disable

namespace spor_proje_api.Migrations
{
    [DbContext(typeof(SporDbContext))]
    [Migration("20251024103215_UcretGuncellemeTablosu")]
    partial class UcretGuncellemeTablosu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("spor_proje_api.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AdminNumarasi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AdminNumarasi")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Adminler");
                });

            modelBuilder.Entity("spor_proje_api.Models.Antrenman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AntrenmanAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AntrenmanTipi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("KaloriYakilan")
                        .HasColumnType("int");

                    b.Property<int>("KalpAtisHizi")
                        .HasColumnType("int");

                    b.Property<string>("Notlar")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SporcuId")
                        .HasColumnType("int");

                    b.Property<int>("Sure")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("UyeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SporcuId");

                    b.HasIndex("UyeId");

                    b.ToTable("Antrenmanlar");
                });

            modelBuilder.Entity("spor_proje_api.Models.Beslenme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Kalori")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Karbonhidrat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ogun")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Protein")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SporcuId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("UyeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Yag")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("YemekAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SporcuId");

                    b.HasIndex("UyeId");

                    b.ToTable("BeslenmeKayitlari");
                });

            modelBuilder.Entity("spor_proje_api.Models.Hedef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("BaslangicTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Birim")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HedefAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("HedefDeger")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("HedefTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kategori")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SporcuId")
                        .HasColumnType("int");

                    b.Property<bool>("Tamamlandi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UyeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SporcuId");

                    b.HasIndex("UyeId");

                    b.ToTable("Hedefler");
                });

            modelBuilder.Entity("spor_proje_api.Models.Performans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Deger")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Kategori")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PerformansAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SporcuId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("UyeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SporcuId");

                    b.HasIndex("UyeId");

                    b.ToTable("Performanslar");
                });

            modelBuilder.Entity("spor_proje_api.Models.PerformansTakibi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("KardiyoSuresi")
                        .HasColumnType("int");

                    b.Property<decimal?>("KasKutlesi")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("Kilo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notlar")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("UyeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("VucutYagOrani")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UyeId");

                    b.ToTable("PerformansTakibi");
                });

            modelBuilder.Entity("spor_proje_api.Models.Sporcu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SporDali")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Yas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sporcular");
                });

            modelBuilder.Entity("spor_proje_api.Models.UcretGuncelleme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("ArtisNedeni")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("EskiUcret")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("GecerlilikTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("GuncelleyenAdminId")
                        .HasColumnType("int");

                    b.Property<int>("UyeId")
                        .HasColumnType("int");

                    b.Property<decimal>("YeniUcret")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GuncelleyenAdminId");

                    b.HasIndex("UyeId");

                    b.ToTable("UcretGuncellemeleri");
                });

            modelBuilder.Entity("spor_proje_api.Models.Uye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcilDurumIletisim")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UyeNumarasi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UyelikTuru")
                        .HasColumnType("int");

                    b.Property<decimal>("UyelikUcreti")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UyeNumarasi")
                        .IsUnique();

                    b.ToTable("Uyeler");
                });

            modelBuilder.Entity("spor_proje_api.Models.Antrenman", b =>
                {
                    b.HasOne("spor_proje_api.Models.Sporcu", "Sporcu")
                        .WithMany("Antrenmanlar")
                        .HasForeignKey("SporcuId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("spor_proje_api.Models.Uye", "Uye")
                        .WithMany("Antrenmanlar")
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Sporcu");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("spor_proje_api.Models.Beslenme", b =>
                {
                    b.HasOne("spor_proje_api.Models.Sporcu", "Sporcu")
                        .WithMany("BeslenmeKayitlari")
                        .HasForeignKey("SporcuId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("spor_proje_api.Models.Uye", "Uye")
                        .WithMany("BeslenmeKayitlari")
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Sporcu");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("spor_proje_api.Models.Hedef", b =>
                {
                    b.HasOne("spor_proje_api.Models.Sporcu", "Sporcu")
                        .WithMany("Hedefler")
                        .HasForeignKey("SporcuId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("spor_proje_api.Models.Uye", "Uye")
                        .WithMany("Hedefler")
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Sporcu");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("spor_proje_api.Models.Performans", b =>
                {
                    b.HasOne("spor_proje_api.Models.Sporcu", "Sporcu")
                        .WithMany("Performanslar")
                        .HasForeignKey("SporcuId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("spor_proje_api.Models.Uye", "Uye")
                        .WithMany("Performanslar")
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Sporcu");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("spor_proje_api.Models.PerformansTakibi", b =>
                {
                    b.HasOne("spor_proje_api.Models.Uye", "Uye")
                        .WithMany()
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("spor_proje_api.Models.UcretGuncelleme", b =>
                {
                    b.HasOne("spor_proje_api.Models.Admin", "GuncelleyenAdmin")
                        .WithMany()
                        .HasForeignKey("GuncelleyenAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("spor_proje_api.Models.Uye", "Uye")
                        .WithMany()
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuncelleyenAdmin");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("spor_proje_api.Models.Sporcu", b =>
                {
                    b.Navigation("Antrenmanlar");

                    b.Navigation("BeslenmeKayitlari");

                    b.Navigation("Hedefler");

                    b.Navigation("Performanslar");
                });

            modelBuilder.Entity("spor_proje_api.Models.Uye", b =>
                {
                    b.Navigation("Antrenmanlar");

                    b.Navigation("BeslenmeKayitlari");

                    b.Navigation("Hedefler");

                    b.Navigation("Performanslar");
                });
#pragma warning restore 612, 618
        }
    }
}
