// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using spor_proje_api.Data;

#nullable disable

namespace spor_proje_api.Migrations
{
    [DbContext(typeof(SporDbContext))]
    [Migration("20251117214052_RemoveUnusedUyeColumns")]
    partial class RemoveUnusedUyeColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Model snapshot kodu buraya gelecek - Entity Framework tarafından otomatik oluşturulacak
#pragma warning restore 612, 618
        }
    }
}

